development:
  adapter: redis
  url: <%= ENV.fetch("REDIS_URL") { "redis://localhost:6379/1" } %>
  channel_prefix: timeless_jeweler_development

test:
  adapter: redis
  url: <%= Rails.application.credentials.redis_url %>
  channel_prefix: timeless_jeweler_test

production:
  adapter: redis
  url: <%= ENV.fetch("REDIS_URL") { "redis://localhost:6379/1" } %>
  channel_prefix: timeless_jeweler_production
