# from https://github.com/gitcoinco/code_fund_ads/blob/master/config/enums.yml
#
# IMPORTANT: All application enums should be defined in this file
#
# They will be made available to the application via: config/initializers/enums.rb
# ...and will be exposed under the ENUMS module
#
# NOTE: Entries in this file can be either key/value or a simple list
#
# Examples
#
#   RATINGS:
#     gold: happy
#     silver: satisfied
#     bronze: sad
#
#   The YAML above will be converted to the following enums
#
#   pry>ENUMS::RATINGS::GOLD       # happy
#   pry>ENUMS::RATINGS::HAPPY      # gold
#   pry>ENUMS::RATINGS::SILVER     # satisfied
#   pry>ENUMS::RATINGS::SATISFIED  # silver
#   pry>ENUMS::RATINGS::BRONZE     # sad
#   pry>ENUMS::RATINGS::SAD        # bronze
#
#   ENUMs also supports the following helper methods
#
#   pry>ENUMS::RATINGS.keys             # [gold, silver, bronze]
#   pry>ENUMS::RATINGS.values           # [happy, satisfied, sad]
#   pry>ENUMS::RATINGS.happy? :gold     # true
#   pry>ENUMS::RATINGS.happy? :bronze   # false
#   pry>ENUMS::RATINGS["happy"]         # gold
#   pry>ENUMS::RATINGS["gold"]          # happy
#
#   ----------------------------------------------------------------------------
#
#   USER_ROLES:
#     - administrator
#     - advertiser
#     - publisher
#
#   The YAML above will be converted to the following enums
#
#   pry>ENUMS::USER_ROLES::ADMINISTRATOR # administrator
#   pry>ENUMS::USER_ROLES::ADVERTISER    # advertiser
#   pry>ENUMS::USER_ROLES::PUBLISHER     # publisher
#
#   pry>ENUMS::USER_ROLES.keys                          # [administrator, advertiser, publisher]
#   pry>ENUMS::USER_ROLES.values                        # [administrator, advertiser, publisher]
#   pry>ENUMS::USER_ROLES.administrator? :administrator # true
#   pry>ENUMS::USER_ROLES.administrator? :publisher     # false
#   pry>ENUMS::USER_ROLES["administrator"]              # administrator
#

ITEM_SOURCES:
  - E
  - B
  - T

ITEM_STYLES:
  - 21st Century
  - Art Deco
  - Art Nouveau
  - Arts and Crafts
  - Baroque
  - Belle Époque
  - Cameo
  - Edwardian
  - Egyptian Revival
  - Ethnic, Tribal
  - Etruscan Revival
  - Georgian
  - Gothic Revival
  - Greek Revival
  - Holiday
  - Late 20th Century
  - Medieval
  - Micro-mosaic
  - Mid-Century
  - Modernist
  - Mourning
  - Native American
  - OOAK One-of-a-Kind
  - Renaissance Revival
  - Retro
  - Revival
  - Russian Empire
  - Russian Revival
  - Victorian
  - Victorian Revival
  - Wedding & Bridal
  - Aesthetic Movement
  - American Classical
  - American Expressionism
  - Ancient
  - Chinese Export
  - Chinoiserie
  - Dutch, Flemish
  - Edo
  - Empire
  - Ethnic Art
  - Handcrafted
  - Ming
  - Modernism
  - Napoleon I
  - Portrait
  - Pre-Columbian
  - Primitive
  - Qing
  - Romantic
  - Romanticism
  - Scandinavian Modern
  - Streamline Moderne
  - William IV

PIECE_CATEGORIES:
  - ring
  - necklace
  - pendant
  - bracelet
  - brooch
  - earring
  - watch

GEMSTONE_CATEGORIES:
  - Agate
  - Alexandrite
  - Amazonite
  - Amber
  - Amethyst
  - Aquamarine
  - Beryl
  - Carnelian
  - Chalcedony
  - Chrysoberyl
  - Chrysoprase
  - Citrine
  - Coral
  - Crystal
  - Diamond
  - Black Diamond
  - Blue Diamond
  - Brown Diamond
  - Pink Diamond
  - White Diamond
  - Yellow Diamond
  - Emerald
  - Garnet
  - Hematite
  - Iolite
  - Jade
  - Kunzite
  - Labradorite
  - Lapis Lazuli
  - Malachite
  - Marcasite
  - Moonstone
  - Morganite
  - Multi-gemstone
  - Onyx
  - Opal
  - Pearl
  - Black Pearl
  - Cultured Pearl
  - Freshwater Pearl
  - Natural Pearl
  - Saltwater Pearl
  - Seed Pearl
  - South Sea Pearl
  - Peridot
  - Quartz
  - Rhinestone
  - Rock Crystal
  - Rubellite
  - Ruby
  - Sapphire
  - Blue Sapphire
  - Green Sapphire
  - Pink Sapphire
  - Star Sapphire
  - Yellow Sapphire
  - Spinel
  - Tanzanite
  - Tiger's Eye
  - Topaz
  - Tourmaline
  - Tsavorite
  - Turquoise
  - Turquoise Matrix
  - Zircon
  - Chrysophrase
  - Rubelite

DIAMOND_CLARITIES:
  - I1
  - I2
  - I3
  - SI1
  - SI2
  - VS1
  - VS2
  - VVS1
  - VVS2
  - IF
  - FL

DIAMOND_CUTS:
  - Excellent
  - Very Good
  - Good
  - Fair
  - Poor

DIAMOND_COLORS:
  - D
  - E
  - F
  - G
  - H
  - I
  - J
  - K
  - L
  - M
  - N
  - O
  - P
  - Q
  - R
  - S
  - T
  - U
  - V
  - W
  - X
  - Y
  - Z

METAL_CATEGORIES:
  - Aluminum
  - Brass
  - Bronze
  - Copper
  - Copper Plate
  - Gold
  - Iron
  - Platinum
  - Silver
  - Sterling Silver
  - Fine Silver
  - Mexican Silver
  - Silver Plate
  - Steel
  - Stainless Steel
  - Titanium
  - Unknown

METAL_COLORS:
  - White
  - Yellow
  - Rose

METAL_PURITIES:
  - 9K
  - 10K
  - 14K
  - 18K
  - 22K
  - 0.800
  - 0.900
  - 0.925
  - 0.950
  - 0.999
  - GF
  - Unknown

STATE_PROVINCES:
  AL: Alabama
  AK: Alaska
  AZ: Arizona
  AR: Arkansas
  CA: California
  CO: Colorado
  CT: Connecticut
  DE: Delaware
  FL: Florida
  GA: Georgia
  HI: Hawaii
  ID: Idaho
  IL: Illinois
  IN: Indiana
  IA: Iowa
  KS: Kansas
  KY: Kentucky
  LA: Louisiana
  ME: Maine
  MD: Maryland
  MA: Massachusetts
  MI: Michigan
  MN: Minnesota
  MS: Mississippi
  MO: Missouri
  MT: Montana
  NE: Nebraska
  NV: Nevada
  NH: New Hampshire
  NJ: New Jersey
  NM: New Mexico
  NY: New York
  NC: North Carolina
  ND: North Dakota
  OH: Ohio
  OK: Oklahoma
  OR: Oregon
  PA: Pennsylvania
  RI: Rhode Island
  SC: South Carolina
  SD: South Dakota
  TN: Tennessee
  TX: Texas
  UT: Utah
  VT: Vermont
  VA: Virginia
  WA: Washington
  WV: West Virginia
  WI: Wisconsin
  WY: Wyoming
