source 'https://rubygems.org'
git_source(:github) { |repo| "https://github.com/#{repo}.git" }

ruby '3.0.0'

# Use ActiveRecord::ActsAs to simulate Multiple Table Inheritance (MTI).
# Read more: https://github.com/manuelmeurer/active_record-acts_as
# FIXME: deprecate use of this gem
gem 'active_record-acts_as'
# Use Active Model has_secure_password
gem 'bcrypt',                    '~> 3.1.7'
gem 'bootsnap',                  '>= 1.4.2', require: false
gem 'browser'
gem 'devise'
gem 'faker', git: 'https://github.com/faker-ruby/faker.git', branch: 'master'
gem 'haml'
gem 'hiredis'
# Build JSON APIs with ease. Read more: https://github.com/rails/jbuilder
# gem 'jbuilder', '~> 2.7'
gem 'jquery-rails'
gem 'money-rails', github: 'juanmanuelramallo/money-rails', branch: 'ruby-3-support-migration-extension'
gem 'pg'
gem 'puma'
gem 'pundit'
gem 'rack-cors',                 '~> 1.1.1'
gem 'rails', github: 'rails/rails'
gem 'rails-controller-testing'
gem 'rails-i18n', '~> 6.0.0'
gem 'redis', '>= 4.0', require: ['redis', 'redis/connection/hiredis']
gem 'redis-session-store'
gem 'sass-rails', '~> 6.0'
gem 'simple_form', github: 'heartcombo/simple_form'
gem 'sprockets', '4.0.0'
gem 'stimulus_reflex', github: 'hopsoft/stimulus_reflex'
gem 'turbolinks',                '~> 5'
gem 'uglifier',                  '~> 3.0'
gem 'view_component', require: 'view_component/engine'
gem 'webpacker', '~> 5.0'

# Use Active Storage variant
# gem 'image_processing', '~> 1.2'

group :development, :test do
  gem 'factory_bot_rails', '~> 6.1.0'
  gem 'pry'
end

group :development do
  gem 'annotate'
  gem 'better_errors'
  # Access an interactive console on exception pages or by calling 'console' anywhere in the code.
  gem 'binding_of_caller'
  gem 'erb_lint', require: false
  gem 'guard'
  gem 'guard-bundler'
  gem 'guard-ctags-bundler'
  gem 'guard-cucumber'
  gem 'guard-minitest'
  gem 'listen'
  gem 'pry-rails'
  gem 'rails-erd'
  # Spring speeds up development by keeping your application running in the background. Read more: https://github.com/rails/spring
  # gem 'spring',                 '2.1.0'
  # gem 'spring-watcher-listen',  '~> 2.0.1'
  gem 'web-console', '>= 3.3.0'
end

group :test do
  gem 'apparition'
  # Adds support for Capybara system testing and selenium driver
  gem 'capybara', '>= 2.15'
  gem 'capybara-slow_finder_errors'
  gem 'cucumber_factory'
  gem 'cucumber-rails', require: false
  gem 'database_cleaner'
  gem 'email_spec'
  gem 'minitest'
  # gem 'minitest-rails-capybara'
  gem 'minitest-reporters'
  gem 'minitest-spec-rails'
  gem 'selenium-webdriver'
  gem 'shoulda', '~> 4.0'
  # Easy installation and use of web drivers to run system tests with browsers
  gem 'webdrivers'
end

group :production do
end

# Windows does not include zoneinfo files, so bundle the tzinfo-data gem
gem 'tzinfo-data', platforms: %i[mingw mswin x64_mingw jruby]

gem 'optimism', '~> 0.4.1'
