name: Rails Best Practices

on:
  push:
    branches: [ master, public ]

jobs:
  rails-best-practices:
    runs-on: ubuntu-latest
    steps:
    - name: Code review using Rails Best Practices
      # You may pin to the exact commit or the version.
      uses: moneyforward/rails_best_practices-action@v0.0.1
      with:
        # Changes the path to a Rails application
        files: # optional

        # Changes `rails_best_practices` command line options.
        # Specify the options in JSON array format.
        # e.g.: '["--vendor", "--spec"]'
        options: # optional

        # Changes the current working directory of the Node.js process
        working_directory: # optional
