name: Test

on:
  push:
    branches: [ master, public ]
    paths:
      - .github/workflows
      - app/**/*
      - db/**/*
      - test/**/*
      - lib/**/*
      - '**/Gemfile*'
      - '!*.md'
  pull_request:
    branches: [ master, public ]
      - .github/workflows
      - app/**/*
      - db/**/*
      - test/**/*
      - lib/**/*
      - '**/Gemfile*'
      - '!*.md'
jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        # Due to https://github.com/actions/runner/issues/849, we have to use
        # quotes for '3.0'
        ruby: ['3.0']

    runs-on: ${{ matrix.os }}
    
    continue-on-error: true

    services:
      postgres:
        image: postgres:12
        env:
          POSTGRES_PASSWORD: postgres
        ports: ['5432:5432']
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
    - uses: actions/checkout@v2
    # see https://github.com/ruby/setup-ruby#versioning
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby }}
        bundler-cache: true # runs 'bundle install' and caches installed gems automatically
    - name: Install required apt packages
      run: |
        sudo apt-get -y install libpq-dev
    - name: Read Node.js version to install from `.nvmrc`
      run: echo "##[set-output name=NVMRC;]$(cat .nvmrc)"
      id: nvm
    - name: Install required Node.js version
      uses: actions/setup-node@v1
      with:
        node-version: "${{ steps.nvm.outputs.NVMRC }}"
    - name: Get Yarn cache directory path
      id: yarn-cache
      run: echo "::set-output name=dir::$(yarn cache dir)"
    - name: Set up cache key and directory for node_modules cache
      uses: actions/cache@v1
      with:
        path: ${{ steps.yarn-cache.outputs.dir }}
        key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
    - name: Yarn install
      run: yarn --frozen-lockfile
    - name: Set up database config
      run: |
        cp config/database.github.yml config/database.yml
    - name: Set up database
      env:
        RAILS_ENV: test
      run: |
        bin/rails db:create
        bin/rails db:schema:load
    - name: Set up Code Climate
      uses: amancevice/setup-code-climate@v0
      with:
        cc_test_reporter_id: d432674f71e0e94044b63a2dd097f8164b8c1e8b88f8f5e66ea815c2de165680
    - name: Code Climate pre-build notification
      run: cc-test-reporter before-build
    - name: Run tests
      run: bin/rails test
      continue-on-error: true
    - name: Code Climate post-build notification
      run: cc-test-reporter after-build


