name: Test

on:
  push:
    branches: [ master, public ]
  pull_request:
    branches: [ master, public ]
jobs:
  test:
    strategy:
      matrix:
        os: [ubuntu-latest]
        # Due to https://github.com/actions/runner/issues/849, we have to use
        # quotes for '3.0'
        ruby: ['3.0']

    runs-on: ${{ matrix.os }}

    services:
      postgres:
        image: postgres:12
        env:
          POSTGRES_PASSWORD: postgres
        ports: ['5432:5432']
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
    - uses: actions/checkout@v2
    # see https://github.com/ruby/setup-ruby#versioning
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby }}
        bundler-cache: true # runs 'bundle install' and caches installed gems automatically
    - name: Install required apt packages
      run: |
        sudo apt-get -y install libpq-dev
    - name: Install Bundler
      run: gem install bundler
    - name: Read Node.js version to install from `.nvmrc`
      run: echo "##[set-output name=NVMRC;]$(cat .nvmrc)"
      id: nvm
    - name: Install required Node.js version
      uses: actions/setup-node@v1
      with:
        node-version: "${{ steps.nvm.outputs.NVMRC }}"
    - name: Get Yarn cache directory path
      id: yarn-cache
      run: echo "::set-output name=dir::$(yarn cache dir)"
    - name: Set up cache key and directory for node_modules cache
      uses: actions/cache@v1
      with:
        path: ${{ steps.yarn-cache.outputs.dir }}
        key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
    - name: Bundle install
      run: |
        bundle config set --local deployment 'false'
        bundle install --jobs 4 --retry 3
    - name: Yarn install
      run: yarn --frozen-lockfile
    - name: Set up database config
      run: |
        cp config/database.github.yml config/database.yml
    - name: Set up database
      env:
        RAILS_ENV: test
      run: |
        bin/rails db:create
        bin/rails db:schema:load
    - name: Run tests
      run: bin/rails test
